version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  tweet_collector:
   
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/get_tweet
    environment:
    - QUERY

    depends_on:
    - mongodb

  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/etl
    env_file:
      - .env
    depends_on:
    - mongodb
    - tweet_collector