version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/get_tweet
    depends_on:
    - mongodb

  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    # environment:
    # - POSTGRES_USER=postgres
    # - POSTGRES_PASSWORD=LandloveR123
    # - POSTGRES_DB=twitter
    env_file:
      - .env

  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/etl
    env_file:
      - .env
    depends_on:
    - mongodb
    - postgresdb
